os: Visual Studio 2017

init:
- ps: >-
    reg ADD "HKLM\Software\Microsoft\StrongName\Verification\*,*" /f

    if ($env:PROCESSOR_ARCHITECTURE -eq "AMD64")

    {
      reg ADD "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification\*,*" /f
    }

build_script:
  - cmd: echo /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" >> msbuild.rsp
  - cmd: msbuild /t:restore /p:Configuration=Release /m
  - cmd: msbuild /t:All /p:Configuration=Release /m

install:
- cmd: git submodule update --init --recursive

# we run the tests ourselves in build.proj for coverage
test: off

deploy:
  - provider: NuGet
    api_key:
      secure: 7MS5+XWaFchMXFqzgneQCqo9U0DlxiPXe/KWWUnbCBDEizVn06EjdQZkWu1gbNOJ
    on:
      branch: /v\d+\.\d+\.\d+/

nuget:
  project_feed: true
  disable_publish_on_pr: false
  
artifacts:
  - path: 'out\*.nupkg'
    name: Package
  - path: 'out\*.vsix'
    name: Extension
  - path: 'msbuild.log'
    name: Log
